export const instrucciones = {
    home: "Selecciona la opcion que quieres. Puedes aprender las letras de Hiragana/Katakana desde 0 o practicarlas si ya las sabes.",
    aprender: `Selecciona cuales Kana quieres aprender y luego presiona 'Aprender' al fondo de la pagina.`,
    practicar: `Selecciona cuales Kana quieres practicar y luego presiona 'Empezar' al fondo de la pagina.`,
    kanatable: `Ingresa en cada tarjeta la lectura en romaji del Kana.(Recuerda apretar 'Enter' para confirmar tu respuesta)`,
    explanation: `Aqui veras un poco de informacion adicional referente a este set de Kanas.`,
    kanalearn:
        "Estudia estas tarjetas para luego responder un Quiz.(Intenta escribir un par de veces estas letras si no las conocias.)",
    kanaquiz:
        "Selecciona de las opciones abajo el romaji correcto, puedes repetir el Quiz las veces que quieras antes de continuar.",
};

export const infotext = {
    あ: "La letra あ(a) se puede confundir con la letra お(o).",
    い: "",
    う: "",
    え: "",
    お: "La letra お(o) se puede confundir con la letra あ(a).",
    か: `La letra か se parece a su contraparte Katakana カ`,
    き: "La parte superior de き se puede ocupar para recordar su contraparte Katakana キ",
    く: ``,
    け: "",
    こ: "La letras こ se parece a su contraparte Katakana コ",
    さ: ``,
    し: `Sonido 'Shi' suave en comparacion a ち 'Chi'.`,
    す: `El sonido de la 'u' en す es muchas veces omitido, por ejemplo です se suele decir 'des'.`,
    せ: `La letra せ se parece a su contraparte Katakana セ`,
    そ: `Ten cuidado con confundir esta letra por el sonido 'Zo' por la forma de la letra parecida a una 'Z'`,
    た: "La letra た se puede confundir con la letra な(na), nota que las dos comparten un tipo de cruz a la izquierda.",
    ち: `Esta letra es una excepcion en la fila de た, su lectura es 'chi'.`,
    つ: `Esta letra es una excepcion en la fila de た, su lectura es 'tsu'.`,
    て: ``,
    と: "",
    な: "La letra な se puede confundir con la letra た(ta), nota que las dos comparten un tipo de cruz a la izquierda.",
    に: "La letra に se puede confundir con la letra こ(ko), no olvides escribir la varita vertical en に.",
    ぬ: "Esta letra comparte la base con otras 2 letras: の(no), め(me), ぬ(nu).",
    ね: "Esta letra comparte la base con otras 2 letras: わ(wa), れ(re), ね(ne).",
    の: "Esta letra comparte la base con otras 2 letras: の(no), め(me), ぬ(nu).",
    は: `La letra は(Ha) se puede confundir con la letra ほ(Ho).`,
    ひ: ``,
    ふ: `Esta letra es un excepcion y su lectura es 'Fu'.`,
    へ: `Tambien puede ser ocupado como particula y su lectura pasa a ser 'E'.`,
    ほ: "La letra ほ(ho) se puede confundir con la letra は(ha) y la letra ま(ma).",
    ま: "Esta letra se puede confundir con la letra ほ(ho).",
    み: "",
    む: "",
    め: "Esta letra comparte la base con otras 2 letras: の(no), め(me), ぬ(nu).",
    も: "La letra も(mo) tiene un parecido con su contraparte Katakana モ(mo).",
    や: `Esta letra se parece a su contraparte Katakana ヤ(ya). El sonido 'ya' se puede confundir con el sonido de じゃ.`,
    ゆ: `El sonido de esta letra 'yu' se puede confundir con el sonido de じゅ.`,
    よ: `El sonido de esta letra 'yo' se puede confundir con el sonido de じょ.`,
    ら: "La letra ら(ra) parece un numero 5 y tambien se parece a su contraparte Katakana ラ(ra).",
    り: "Esta letra es parecida a su contraparte Katakana リ(ri).",
    る: "La letra る(ru) se puede confundir con la letra ろ(ro).",
    れ: "Esta letra comparte la base con otras 2 letras: わ(wa), れ(re), ね(ne).",
    ろ: "La letra ろ(ro) se puede confundir con la letra る(ru).",
    わ: "Esta letra comparte la base con otras 2 letras: わ(wa), れ(re), ね(ne).",
    を: `Esta letra es solo ocupada como particula en frases y si bien su escritura Romaji es 'wo' se dice 'o'.`,
    ん: `La unica consonante solitaria.`,
    が: "La marca Dakuten: ゛se utiliza para cambiar el sonido de las letras.",
    ぎ: `El sonido de 'K' pasa a ser 'G'.`,
    ぐ: `El sonido de 'K' pasa a ser 'G'.`,
    げ: `El sonido de 'K' pasa a ser 'G'.`,
    ご: `El sonido de 'K' pasa a ser 'G'.`,
    ざ: `La marca Dakuten: ゛se utiliza para cambiar el sonido de las letras, en este caso el sonido 'sa' pasa a ser 'za'.`,
    じ: `La letra 'shi' es un caso especial, el sonido 'shi' pasa a ser 'lli' pero recuerda escribirlo con 'J'.`,
    ず: `El sonido 'su' pasa a ser 'zu'.`,
    ぜ: `El sonido 'se' pasa a ser 'ze'.`,
    ぞ: `El sonido 'so' pasa a ser 'zo'.`,
    だ: `La marca Dakuten: ゛se utiliza para cambiar el sonido de las letras, en este caso el sonido 'ta' pasa a ser 'da'.`,
    ぢ: `La letra ぢ es un caso especial, el sonido pasa de 'chi' a 'lli' tal como じ pero para escribirla en un teclado tienes que escribir "di".`,
    づ: `La letra づ es un caso especial, el sonido pasa de 'tsu' a algo como 'dzu'. Para escribirla en un te clado ingresa "du".`,
    で: `El sonido 'te' pasa a ser 'de'.`,
    ど: `El sonido 'to' pasa a ser 'do'.`,
    ば: `La marca Dakuten: ゛se utiliza para cambiar el sonido de las letras, en este caso el sonido 'ja' pasa a ser 'ba', recuerda que el romaji se escribe con "H".`,
    び: `El sonido 'ji' pasa a ser 'bi', recuerda que el Romaji se escribe con "H".`,
    ぶ: `Si bien ふ es una letra especial y su sonido original es 'fu', con Dakuten sigue la reglar y suena 'bu'.`,
    べ: `El sonido 'je' pasa a ser 'be'.`,
    ぼ: `El sonido 'jo' pasa a ser 'zu'.`,
    ぱ: `La marca Dakuten: ゛se utiliza para cambiar el sonido de las letras, en este caso el sonido 'ja' pasa a ser 'pa'.`,
    ぴ: `El sonido 'ji' pasa a ser 'pi'.`,
    ぷ: `Si bien ふ es una letra especial y su sonido original es 'fu', con Dakuten sigue la reglar y suena 'pu'.`,
    ぺ: `El sonido 'je' pasa a ser 'pe'.`,
    ぽ: `El sonido 'jo' pasa a ser 'po'.`,
    きゃ: "",
    きゅ: "",
    きょ: "",
    しゃ: "",
    しゅ: "",
    しょ: "",
    ちゃ: "",
    ちゅ: "",
    ちょ: "",
    にゃ: "",
    にゅ: "",
    にょ: "",
    ひゃ: "",
    ひゅ: "",
    ひょ: "",
    みゃ: "",
    みゅ: "",
    みょ: "",
    りゃ: "",
    りゅ: "",
    りょ: "",
    ぎゃ: "",
    ぎゅ: "",
    ぎょ: "",
    じゃ: "",
    じゅ: "",
    じょ: "",
    びゃ: "",
    びゅ: "",
    びょ: "",
    ぴゃ: "",
    ぴゅ: "",
    ぴょ: "",
    ア: "",
    イ: "",
    ウ: "",
    エ: "",
    オ: "",
    カ: "",
    キ: "",
    ク: "",
    ケ: "",
    コ: "",
    サ: "",
    シ: "",
    ス: "",
    セ: "",
    ソ: "",
    タ: "",
    チ: "",
    ツ: "",
    テ: "",
    ト: "",
    ナ: "",
    ニ: "",
    ヌ: "",
    ネ: "",
    ノ: "",
    ハ: "",
    ヒ: "",
    フ: "",
    ヘ: "",
    ホ: "",
    マ: "",
    ミ: "",
    ム: "",
    メ: "",
    モ: "",
    ヤ: "",
    ユ: "",
    ヨ: "",
    ラ: "",
    リ: "",
    ル: "",
    レ: "",
    ロ: "",
    ワ: "",
    ヲ: "",
    ン: "",
    ガ: "",
    ギ: "",
    グ: "",
    ゲ: "",
    ゴ: "",
    ザ: "",
    ジ: "",
    ズ: "",
    ゼ: "",
    ゾ: "",
    ダ: "",
    ヂ: "",
    ヅ: "",
    デ: "",
    ド: "",
    バ: "",
    ビ: "",
    ブ: "",
    ベ: "",
    ボ: "",
    パ: "",
    ピ: "",
    プ: "",
    ペ: "",
    ポ: "",
    キャ: "",
    キュ: "",
    キョ: "",
    シャ: "",
    シュ: "",
    ショ: "",
    チャ: "",
    チュ: "",
    チョ: "",
    ニャ: "",
    ニュ: "",
    ニョ: "",
    ヒャ: "",
    ヒュ: "",
    ヒョ: "",
    ミャ: "",
    ミュ: "",
    ミョ: "",
    リャ: "",
    リュ: "",
    リョ: "",
    ギャ: "",
    ギュ: "",
    ギョ: "",
    ジャ: "",
    ジュ: "",
    ジョ: "",
    ビャ: "",
    ビュ: "",
    ビョ: "",
    ピャ: "",
    ピュ: "",
    ピョ: "",
    ツァ: "",
    ファ: "",
    ヴァ: "",
    ウィ: "",
    ティ: "",
    フィ: "",
    ディ: "",
    ヴィ: "",
    セィ: "",
    トゥ: "",
    ドゥ: "",
    デュ: "",
    フュ: "",
    ウェ: "",
    シェ: "",
    チェ: "",
    ツェ: "",
    フェ: "",
    ジェ: "",
    ヴェ: "",
    ウォ: "",
    ツォ: "",
    フォ: "",
    ヴォ: "",
};

export const explanationtext = {
    あ: `Estas 5 kanas corresponden a los sonidos de las vocales, su orden es diferente al del español : 
        \n'a, i, u, e, o'. 
        \n\n Este mismo orden se repite con las demas letras, por ejemplo : \n 'ka, ki, ku, ke, ko', \n 'ma, mi, mu, me, mo'.`,
    か: `Las letras de la fila か representan los sonidos:
        \nKa, Ki, Ku, Ke, Ko.
        \n\nLa fila de か se puede transformar del sonido de 'K' a el sonido de 'G' suave con la marca Dakuten ゛.
        \n\nPor ejemplo け = Ke, pero げ = Ge como en 'Guerra'.`,
    さ: `La fila de la letra さ representa los sonidos de la letra 'S', suena como uno lo esperaria, con la excepcion de し que se lee y escribe 'Shi'.
        \n\nPara lograr los sonidos con Z se ocupan estas mismas letras pero con la marca Dakuten ゛.
        \nPor ejemplo そ = so, pero ぞ = zo.
        \nEl sonido de し pasa a ser 'lli' de 'apellido' cuando se le agrega dakuten, pero es escrito con 'J'.
        \nEntonces, じ se escribe "ji" pero se dice 'lli'.`,
    た: `La fila de た representa los sonidos de la letra 'T', existen 2 excepciones, ち y つ que son escritas como "Chi" y "Tsu" respectivamente.
        \nLa letra つ tiene una forma mini (つ tsu grande, っ tsu chico) se puede ocupar para 'duplicar' la consonante que la sigue, por ejemplo : \nあさって(asatte), ざっし(zasshi).
        \nSi necesitas escribir esta version mini por si sola o cualquier otra de las versiones minis de las letras solo agrega una 'x' primero, asi : \n'xtsu' = 'っ', 'xya' = 'ゃ'.
        \nLa fila de た se puede transformar del sonido de 'T' a el sonido de 'D' con la marca Dakuten ゛.
        \nPor ejemplo と = To, pero ど = Do.
        \nLa letra ぢ cambia al sonido 'lli' al igual que じ pero para escribir ぢ en teclado tienes que escribir "di".
        \nLa letra づ cambia a un sonido como 'dzu' y para escribirlo en teclado tienes que escribir "du".`,
    な: ``,
    は: `La lectura de la fila は es como la J en el español, は suena como 'Ja' en 'Jabon', へ suena como 'Je' en 'Jefa' pero cuando escribes el romaji debe ser con la letra "H".
        \nLa letra 'は' en especifico puede ser utilizada como particula y en tal caso su lectura es 'Wa'.
        \nLa letra へ puede ser ocupado como particula tambien y en tal caso su lectura es 'E'.
        \nEsta fila puede pasar del sonido 'J' al sonido 'B' y 'P' con Dakuten ゛ y Handakuten ゜respectivamente. Por ejemplo ひ(hi), び(bi), ぴ(pi).
        \nDentro de esta fila la letra ふ es una excepcion y su lectura y escritura es 'Fu'.`,
    ま: ``,
    や: `Esta fila representa los sonidos de la letra 'Y'.
        \n'Ya, Yu, Yo'
        \nSolo contiene 3 letras pero estas tambien pueden ser utilizadas mezclandolas con otras Kanas de la linea 'i' como き(ki), に(ni), etc.
        \nPara hacer estas combinaciones la letra debe estar en su version mini,\n や = Ya grande, ゃ = Ya mini.
        \nPor ejemplo: きゃ(kya), りゅ(ryu), みょ(myo).
        \n\nTen cuidado con las letras し y ち ya que combinados con esta fila pierden el sonido 'Y'.
        \nEntonces: \nしゃ(sha), しゅ(shu)、しょ(sho). \nちゃ(cha), ちゅ(chu), ちょ(cho).`,
    ら: ``,
    わ: `Esta fila representa los sonidos de la letra 'W'* y solo contiene 2 letras, わ(wa) y を(wo).
        \n*を es solo ocupada como particula dentro de frases y se dice 'o'.
        \nLa letras ん no forma parte de esta fila pero fue agregada aqui para simplificar los botones.
        Para escribir la letra ん en teclado tienes que escribir lo siguiente 'nn'.
        \nRecuerda que para los sonidos 'na', 'ni', 'nu', 'ne', 'no' ya existen Kanas y no puedes combinar la letra ん con las vocales para crear esos sonidos.`,
    が: ``,
    ざ: ``,
    だ: ``,
    ば: ``,
    ぱ: ``,
    きゃ: ``,
    しゃ: ``,
    ちゃ: ``,
    にゃ: ``,
    ひゃ: ``,
    みゃ: ``,
    りゃ: ``,
    ぎゃ: ``,
    じゃ: ``,
    びゃ: ``,
    ぴゃ: ``,
    ア: ``,
    カ: `Reemplaza algunas silabas de la letra 'C' del español como 'Ca' en 'Camion', 'Cu' como en 'Cuello' y 'Co' de 'Comida'.
        \nSonidos como 'Que', 'Qui' tambien pueden ser representados con estas letras.`,
    サ: ``,
    タ: ``,
    ナ: ``,
    ハ: ``,
    マ: ``,
    ヤ: ``,
    ラ: ``,
    ワ: ``,
    ガ: ``,
    ザ: ``,
    ダ: ``,
    バ: ``,
    パ: ``,
    キャ: ``,
    シャ: ``,
    チャ: ``,
    ニャ: ``,
    ヒャ: ``,
    ミャ: ``,
    リャ: ``,
    ギャ: ``,
    ジャ: ``,
    ビャ: ``,
    ピャ: ``,
    ツァ: ``,
    ウィ: ``,
    トゥ: ``,
    ウェ: ``,
    ウォ: ``,
};

export const bigButtonExplanations = {
    learn: "Selecciona cuales Kana quieres aprender, te mostraremos información y tips sobre ellos para que los puedas recordar y diferenciar entre sí, después de cada set tendrás un pequeño quiz para reforzar lo que aprendiste.",
    practice: `Si ya sabes algunos Kanas pero quieres practicar su lectura.
    Los Kanas que selecciones para practicar serán revueltos para que nunca estén en el mismo orden. Puedes seguir estudiando el mismo set o seleccionar otro set de Kanas.
`,
};

export function KanaToInfo(kana) {
    if (infotext[kana] === "") {
        return "...";
    }

    let symbol = "ⓘ ";
    let info = symbol.concat(infotext[kana]);

    if (info != null) {
        return info;
    }
}
